{{- if contains "android" .osid -}}
[".config/helium314.keyboard/libjni_latinimegoogle.so"]
    type = "file"
    url = "https://raw.githubusercontent.com/erkserkserks/openboard/master/app/src/main/jniLibs/arm64-v8a/libjni_latinimegoogle.so"
{{- end -}}